app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

how_it_works:
    path: /how-it-works
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/howItWorks.html.twig

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/about.html.twig

terms:
    path: /terms
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/terms.html.twig
