# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - @fos_user.user_manager
            - {facebook: facebookId}

    email_sender:
        class: AppBundle\Service\EmailSender
        arguments:
            - @mailer
            - @templating

    event_listener.send_connection_created_email:
        class: AppBundle\EventListener\SendConnectionCreatedEmailListener
        arguments:
            - @email_sender
        tags:
            - { name: kernel.event_listener, event: connection.created, method: whenConnectionCreated }
